### ISSUE TITLE
Event in tf2

### ISSUE THREAD

**Issue by aakash94** [Spenhouet/tensorboard-aggregator#4]
**bug**
unable to import 
`tensorflow.core.util.event_pb2 import Event`
Unresolved reference Event
**Desktop :**
 - OS: Windows 10
 - python version : 3.7
 - tensorflow version : 2.0
 - numpy version : 1.17.2

**Comment by aakash94** [comment]
Probably something to do with tf itself.

**Comment by Spenhouet** [comment]
@aakash94 Yes, tensorboard-aggregator was only tested and implemented for tensorflow 1.x

I currently don't have the time to write an updated version for tensorflow 2.x
