### ISSUE TITLE
Extracting stored Hyperparameters

### ISSUE THREAD

**Issue by andreifoldes** [Spenhouet/tensorboard-aggregator#5]
I think it would be really useful if this could be extended to extract hyperparameters that are logged in HParams objects

**Comment by Spenhouet** [comment]
Sorry for the late response and thank you for your suggestion.

This project is mainly about calculating the statistics like max, min, mean, ... of measures over the curse of training. Extracting data to CSV is a useful way to plot this data for papers but that is not the focus of this project. I would like to keep it about that.
