### ISSUE TITLE
readme link to tensorboard-reducer for PyTorch?

### ISSUE THREAD

**Issue by janosh** [Spenhouet/tensorboard-aggregator#8]
I created a [`pip`-installable package](https://pypi.org/project/tensorboard-reducer) with similar functionality to this repo over at https://github.com/janosh/tensorboard-reducer.

It's targeted at PyTorch users and doesn't require a TensorFlow installation. How about we each add a readme link to the other's repo suggesting users of the other framework look there instead?

**Comment by Spenhouet** [comment]
Hi @janosh,

this tool was not targeted at tensorflow users specifically. It should also be useable by pytorch users. 
In the last year I did not really had any use for it myself and therefore did not actively maintain it or nicely package it as you did.
Maybe I will in the future.

I nonetheless added a readme link to your project, see: https://github.com/Spenhouet/tensorboard-aggregator/blob/master/README.md

**Comment by janosh** [comment]
> I nonetheless added a readme link to your project, ...

Thanks a lot! [Same here](https://github.com/janosh/tensorboard-reducer/commit/72a9b2a9fe0dc60e504ce6cd4d5d565cdbdffb8e#diff-5a831ea67cf5cf8703b0de46901ab25bd191f56b320053be9332d9a3b0d01d15R14-R15). No need to mention me by name in your readme though. 😅

> this tool was not targeted at tensorflow users specifically. It should also be useable by pytorch users.

Since you're importing `tf.summary` and `Event` from `tensorflow.core.util.event_pb2`, this tool does require a TF 1.x installation, if I'm not mistaken. Since most of ML research uses PyTorch these days and TF 1.x usage is shrinking, I thought I'd be good to have a tool without that dependency as well.

**Comment by Spenhouet** [comment]
> No need to mention me by name in your readme though.

Would you prefer that I remove your name from there?

> this tool does require a TF 1.x installation

That is true. I don't really see the problem with that since it is just another python package someone needs to have installed. A thing of some seconds. I therefore do not worry to much about the summary being written by TF or pytorch.

EDIT: The only issue is that TF 1.x is relatively out-dated by now. If I would update this package, I would probably also do it with pytorch.

**Comment by janosh** [comment]
> Would you prefer that I remove your name from there?

Sure, I'm all for brevity. :)

**Comment by Spenhouet** [comment]
No problem. Done :)
